description: 
datelastupdated: July, 2022
fullnameofperson: Leanne Stockwell
selfIdentification: Acting Discipline Librarian | Griffith Library
colour1: "#9AECDC"  # sidebar background 
colour2: "#363E45"  # colour of name and desc
colour3: "#363E45"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#A4A4A4" # menu link colour when hover
