description: All about me
datelastupdated: Nov 2021
fullnameofperson: Belinda Weaver
selfIdentification: Head, Academic Engagement Services, Griffith University Library
colour1: "#2F4F4F"  # sidebar background 
colour2: "#a3cef1"  # colour of name and desc
colour3: "#a3cef1"  # colour of Menu links
colour4: "#d4dfc7" # trying to be background colour - still experimenting 
colour5: "#e7ecef" # menu link colour when hover
