description: 
datelastupdated: July, 2022
fullnameofperson: Leanne Stockwell
selfIdentification: Acting Discipline Librarian | Griffith Library
colour1: "#B5C9D5"  # sidebar background 
colour2: "#363E45"  # colour of name and desc
colour3: "#363E45"  # colour of Menu links
colour4: "#ECF4F9" # trying to be background colour - still experimenting 
colour5: "#A4A4A4" # menu link colour when hover
